### ISSUE TITLE
Add social icons to the top bar

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-Collaborative-20#10]
Add social icons with open code social links

**Comment by cyber-venom003** [comment]
Sir....Please assign me this task!!!

**Comment by Rohini13** [comment]
@opencodebot claim

**Comment by ananya-mohanty** [comment]
@opencodebot claim

**Comment by thesmallstar** [comment]
@Rohini13  there is no opencodebot :) 
Cybervenom commented first so assigning to him 
Please solve another issue and/or explore more repos :D

**Comment by Piyush4064** [comment]
Sir, I want to contribute in this task

**Comment by garvitchittora** [comment]
I want to work on this project

**Comment by ekanban** [comment]
@Piyush4064 @garvitchittora the issue has already been assigned to @cyber-venom003. Please look at some other issues/repos!

**Comment by thesmallstar** [comment]
@cyber-venom003  any updates

**Comment by cyber-venom003** [comment]
> @cyber-venom003 any updates

Right now....working on projects section
Please assign this task to any one else!!
Sorry sir.

**Comment by thesmallstar** [comment]
@Rohini13  assigned to you.

**Comment by JLodha** [comment]
Claim

**Comment by ananya-mohanty** [comment]
Claim

**Comment by blaze-assault** [comment]
Can i claim this sir..since there is no pr

**Comment by JLodha** [comment]
Sir i want to work on this issue
This issue has been inactive since the last 3 days

**Comment by garvitchittora** [comment]
Sir i want to work on this issue
This issue has been inactive since the last 4 days

**Comment by blaze-assault** [comment]
Claim .it has been inactive

**Comment by blaze-assault** [comment]
claim
