### ISSUE TITLE
Create a footer for the website

### ISSUE THREAD

**Issue by ekanban** [opencodeiiita/Opencode-Collaborative-20#2]
Things required in the footer:

Logos of IIITA and GeekHaven on the left side.
OpenCode's social media links in the center-> [Facebook](https://www.facebook.com/opencodeiiita/), [Twitter](https://twitter.com/teamOpencode/) and [GitHub](https://github.com/opencodeiiita).
OpenCode's logo on the right side.

**Comment by Swarnam97** [comment]
claim

**Comment by ekanban** [comment]
The event hasn't started yet @Luna-Lovegood97
Check back again 12 midnight.

**Comment by ekanban** [comment]
@Luna-Lovegood97 would you like to take this up now?

**Comment by Swarnam97** [comment]
yes, claim

**Comment by ekanban** [comment]
Go ahead

**Comment by garvitchittora** [comment]
I want to work on this project

**Comment by Mridul20** [comment]
Sir I want to contribute on this project

**Comment by amit2223** [comment]
sir i want to work on this project.

**Comment by naina24** [comment]
@opencodebot claim

**Comment by deepakgupta124** [comment]
sir I Want to workon this project

**Comment by deepak-gup7a** [comment]
sir I want To work On this project

**Comment by rox999** [comment]
sir i want to work on this project

**Comment by JLodha** [comment]
Claim

**Comment by ekanban** [comment]
Updates @Luna-Lovegood97.
Please reply before 4pm today, otherwise I'll have to reassign this issue to someone.

**Comment by ekanban** [comment]
Assigned to @garvitchittora due to no reply from @Luna-Lovegood97
