### ISSUE TITLE
Project repository link should open in new tab

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-20#281]
When you click on the Project Repository button, it should open in a new tab.

![image](https://user-images.githubusercontent.com/28949397/73022480-ae8c7300-3e4f-11ea-96fb-27b3ee09a25c.png)

**Comment by starboi02** [comment]
claim

**Comment by griffy06** [comment]
claim

**Comment by Mridul20** [comment]
claim

**Comment by JLodha** [comment]
I want to work on this sir

**Comment by kumarmanish03** [comment]
Claim

**Comment by zevnil** [comment]
claim

**Comment by infern018** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by starboi02** [comment]
@zerefwayne please assign the task

**Comment by blaze-assault** [comment]
Claim

**Comment by starboi02** [comment]
@zerefwayne please assign the task

**Comment by kumarmanish03** [comment]
https://manish-kumar-2000.github.io/Opencode20/

task done

**Comment by starboi02** [comment]
@manish-kumar-2000 I was the first person to claim it ,I didn't make pull request, as was not assigned.How could you create the pull request without being assigned?
