### ISSUE TITLE
Align projects section links and data

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-Collaborative-20#290]
![image](https://user-images.githubusercontent.com/42006277/73102882-cc71da80-3f18-11ea-9fd8-0d8c3f76c7c2.png)

1. Heading should come in one line 
2. project links should be in one line

**Comment by ananya-mohanty** [comment]
claim

**Comment by pradhuman1** [comment]
claim

**Comment by garvitchittora** [comment]
claim

**Comment by sarthakm21** [comment]
Claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by kumarmanish03** [comment]
CLAIM

**Comment by blaze-assault** [comment]
Claim
