### ISSUE TITLE
Add a timer above hero image 

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-Collaborative-20#291]
It should show the number of days hours and seconds left.

**Comment by ananya-mohanty** [comment]
claim

**Comment by thesmallstar** [comment]
You already have 2 issues claimed, still open.

**Comment by pradhuman1** [comment]
claim

**Comment by JLodha** [comment]
Claim

**Comment by garvitchittora** [comment]
claim

**Comment by sarthakm21** [comment]
Claim

**Comment by blaze-assault** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by kumarmanish03** [comment]
CLAIM

**Comment by ananya-mohanty** [comment]
Claim (Its been more than two days)

**Comment by pradhuman1** [comment]
@ananya-mohanty it is not more than two days and @thesmallstar i almost completed it just give some more time i will do it

**Comment by pradhuman1** [comment]
Sir Website changed so much should i add timer

**Comment by blaze-assault** [comment]
Claim

**Comment by pradhuman1** [comment]
> Sir Website changed so much should i add timer

Sir I m ready with code I m not adding because  website has some bugs(student section not visible)

**Comment by sggts04** [comment]
can I work on this?
