### ISSUE TITLE
Create the first version of the landing page

### ISSUE THREAD

**Issue by ekanban** [opencodeiiita/Opencode-Collaborative-20#3]
Alright then, let's start building the first basic version of this website's landing page (the front page or the first thing that you see when you open the website)
A good place to start can be putting up a nice background with OpenCode's logo in the middle.

**Comment by Rohini13** [comment]
@opencodebot claim

**Comment by Rohini13** [comment]
@opencodebot claim

**Comment by garvitchittora** [comment]
I want to work on this project

**Comment by thesmallstar** [comment]
@garvitchittora  this issue is assigned to  @Rohini13 , please explore more issues/repos

**Comment by amit2223** [comment]
sir i want to work on this project.

**Comment by rox999** [comment]
sir i want to work on this project.

**Comment by JLodha** [comment]
Claim

**Comment by ekanban** [comment]
@Rohini13 any updates?
Please reply before 4pm today, otherwise I'll have to reassign this issue to someone.

**Comment by Rohini13** [comment]
@Ace-Bansal Sir, I made two pull requests for this issue
