### ISSUE TITLE
Remove unnecessary Options from the Navbar and add relevant ones and correctly link them

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-20#368]
![Screenshot from 2020-02-12 19-25-40](https://user-images.githubusercontent.com/32068121/74341406-aa5bd180-4dcd-11ea-9193-be48c95ecf95.png)

**Comment by sarthakm21** [comment]
claim

**Comment by Jigar3** [comment]
@sarthakm21 go ahead

**Comment by sarthakm21** [comment]
what options should I add?

**Comment by Jigar3** [comment]
Projects and Participants

**Comment by pradhuman1** [comment]
claim
