### ISSUE TITLE
Align the "About OpenCode" Section Properly

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-20#369]
![Screenshot from 2020-02-12 19-27-26](https://user-images.githubusercontent.com/32068121/74341500-d5debc00-4dcd-11ea-98da-1f67135716dd.png)

Remove or edit the grey bars

**Comment by sarthakm21** [comment]
claim

**Comment by Jigar3** [comment]
@sarthakm21 go ahead

**Comment by pradhuman1** [comment]
claim
