### ISSUE TITLE
Edit the OpenCode Project Section 

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-20#370]
The Projects are miserably aligned and no structure is there.
Align the contents properly and enclose them within a card.

Some sample card designs are attached for reference.
![Screenshot from 2020-02-12 19-31-21](https://user-images.githubusercontent.com/32068121/74341826-6917f180-4dce-11ea-80bf-5e274b950001.png)
![Screenshot from 2020-02-12 19-31-07](https://user-images.githubusercontent.com/32068121/74341830-6b7a4b80-4dce-11ea-85ce-c7b5590863e6.png)

**Comment by blaze-assault** [comment]
Claim

**Comment by Jigar3** [comment]
@blaze-assault go ahead

**Comment by sarthakm21** [comment]
claim

**Comment by kumarmanish03** [comment]
claim

**Comment by blaze-assault** [comment]
https://blaze-assault.github.io/Opencode-Collaborative-20a/

**Comment by blaze-assault** [comment]
@Jigar3  @thesmallstar  please review the pr
