### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-20#371]
The current footer looks really bad. Add a cool footer and link all the social networks within it.
Make sure alignment is proper in every resolution

**Comment by Cybertron-Avneesh** [comment]
claim

**Comment by Jigar3** [comment]
@Cybertron-Avneesh Go Ahead

**Comment by sarthakm21** [comment]
claim

**Comment by aarpit1010** [comment]
Claim

**Comment by garvitchittora** [comment]
claim
