### ISSUE TITLE
Add participants Section

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-Collaborative-20#5]
Fetch Data from participants.json 
It should display the name and most of the information in JSON.

**Comment by Saggittarius-A** [comment]
@opencodebot claim

**Comment by Saggittarius-A** [comment]
1

**Comment by kavi-12** [comment]
@opencodebot claim

**Comment by rox999** [comment]
sir i want to work on this project.

**Comment by ekanban** [comment]
@iit2019017 any updates on this? Do you need any help?

**Comment by ekanban** [comment]
@iit2019017 updates? 
Please reply before 4pm today, otherwise I'll have to reassign this issue to someone.

**Comment by ekanban** [comment]
Assigned to @kavi-12 due to no reply from @iit2019017

**Comment by ekanban** [comment]
you'll have to iterate over the json file and display the text in index.html
Try having a look at this [thread](https://stackoverflow.com/questions/34907982/looping-through-json-data-to-generate-html)

**Comment by kavi-12** [comment]
sir, participants.json file is a large file ....do we have to display name and details of all the participants in the index.html
