### ISSUE TITLE
Add Mentors Section 

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-Collaborative-20#6]
Fetch mentors from mentors.json

**Comment by sarthakm21** [comment]
can i do this

**Comment by sggts04** [comment]
claim

**Comment by uglyprincess** [comment]
@opencodebot claim

**Comment by kavi-12** [comment]
@opencodebot claim

**Comment by karan-kunwar** [comment]
I want to work on this.

**Comment by thesmallstar** [comment]
@sarthakm21  go ahead

**Comment by rox999** [comment]
sir i want to working on this.

**Comment by ekanban** [comment]
@sarthakm21 any updates on this? Do you need any help?

**Comment by sarthakm21** [comment]
@Ace-Bansal Still looking into it sir. This is new for me.
Can you recommend some related write-ups that might help me out?

**Comment by ekanban** [comment]
@sarthakm21 you'll have to iterate over the json file and display the text in index.html
Try having a look at this thread:
https://stackoverflow.com/questions/34907982/looping-through-json-data-to-generate-html

**Comment by ekanban** [comment]
@sarthakm21 were you able to make any progress?

**Comment by kavi-12** [comment]
claim

**Comment by sarthakm21** [comment]
@Ace-Bansal I went through the the thread and am working on it.

**Comment by sggts04** [comment]
Can I work on this? Its been 2 days

**Comment by cyber-venom003** [comment]
claim

**Comment by grenmon2202** [comment]
claim

**Comment by kumarmanish03** [comment]
**CLAIM**

**Comment by cyber-venom003** [comment]
@Ace-Bansal Please assign it to me sir....the issue has been inactive for past 2 days!!

**Comment by maniacric** [comment]
CLAIM

**Comment by mendelevium28** [comment]
Can i take up the issue?

**Comment by sggts04** [comment]
claim

**Comment by thesmallstar** [comment]
Issue reopened, comment to claim.

**Comment by sggts04** [comment]
claim
