### ISSUE TITLE
Add move to top button 

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-Collaborative-20#8]
it should be floating in bottom right side

**Comment by Codedude1** [comment]
I wanna work on this

**Comment by griffy06** [comment]
@opencodebot claim

**Comment by griffy06** [comment]
@opencodebot claim

**Comment by garvitchittora** [comment]
I want to work on this project

**Comment by Mridul20** [comment]
Sir I want to contribute on this project

**Comment by ekanban** [comment]
@griffy06 we're not using opencodebot, will be removing it soon. 
@Codedude1 commented first so assigning the issue to him

**Comment by JLodha** [comment]
Claim

**Comment by ekanban** [comment]
@Codedude1 updates?
Please reply before 4pm today or I'll have to reassign this issue to someone else.

**Comment by Codedude1** [comment]
@Ace-Bansal  Sir, I have opened a PR.
